CREATE TABLE IF NOT EXISTS uzer (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(32) DEFAULT "Anon",
    email VARCHAR(255) NOT NULL,
    password VARCHAR(72) NOT NULL,
    is_deleted BOOLEAN DEFAULT false,
    deleted_at DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS category (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uzer_id INT NOT NULL REFERENCES uzer(id) ON DELETE CASCADE,
    name VARCHAR(32) DEFAULT "My Category",
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uzer_id INT NOT NULL REFERENCES uzer(id) ON DELETE CASCADE,
    category_id INT NOT NULL REFERENCES category(id) ON DELETE CASCADE,
    name VARCHAR(32) DEFAULT "My Project",
    description TEXT,
    status ENUM('CREATED', 'STARTED', 'COMPLETED', 'PAUSED', 'STOPPED') DEFAULT 'CREATED',
    priority ENUM('LOWEST', 'LOW', 'MEDIUM', 'HIGH', 'HIGHEST') DEFAULT 'MEDIUM',
    start_time DATETIME,
    end_time DATETIME,
    due_time DATETIME,
    estimated_hr DOUBLE,
    daily_hr DOUBLE,
    is_deleted BOOLEAN DEFAULT false,
    deleted_at DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS task (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uzer_id INT NOT NULL REFERENCES uzer(id) ON DELETE CASCADE,
    project_id INT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    description TEXT,
    status ENUM('GENERATED', 'PLANNED', 'COMPLETED') DEFAULT 'GENERATED',
    priority ENUM('LOWEST', 'LOW', 'MEDIUM', 'HIGH', 'HIGHEST') DEFAULT 'MEDIUM',
    start_time DATETIME,
    duration_hr DOUBLE DEFAULT 2,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);