version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: odaat
      MYSQL_DATABASE: odaat
      MYSQL_USER: odaat
      MYSQL_PASSWORD: odaat
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - odaat-network

  backend:
    build:
      context: ./spring-server/odaat
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/odaat
    ports:
      - "9000:9000"
    networks:
      - odaat-network

  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    networks:
      - odaat-network

networks:
  odaat-network:
    driver: bridge

volumes:
  mysql_data: