spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/odaat
spring.datasource.username=dev
spring.datasource.password=dev23

server.port=9090